DB settings, connected with swagger
koaptiv/lazychef pull request #2
Opened 2022-04-08 18:57 UTC by ganados

2022-04-09 08:50 UTC, fizo99 commented on src/main/java/com/koapti/lazychef/LazychefApplication.java
> +@SpringBootApplication()
potrzebujemy () ?

2022-04-09 08:50 UTC, fizo99 commented on src/main/java/com/koapti/lazychef/configuration/swagger/SwaggerConfig.java
> +                .forPaths(PathSelectors.any())
deprecated metoda

2022-04-09 08:50 UTC, fizo99 commented on src/main/java/com/koapti/lazychef/configuration/swagger/SwaggerConfig.java
> +        AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
moze lepiej         
var authorizationScopes = new AuthorizationScope[] {
                new AuthorizationScope("global", "accessEverything")
}; ?

2022-04-09 08:50 UTC, fizo99 commented on src/main/resources/application.properties
> +spring.config.import=credentials.properties
jesli importujemy jakies propsy to przydalby sie w repo ich wzorzec bez wartosci

2022-04-09 08:50 UTC, fizo99 commented on src/main/resources/application.properties
> +spring.datasource.username = ${USERNAME_LOGIN}
USERNAME_LOGIN? nie powinno byc samo USERNAME albo samo LOGIN?
zrobilbym ta propke i ta nizej tak samo jak dla security czyli
DATASOURCE_USERNAME i DATASOURCE_PASSWORD

2022-04-09 09:45 UTC, fizo99 commented on src/main/java/com/koapti/lazychef/configuration/swagger/SwaggerConfig.java
> +                .forPaths(PathSelectors.any())
https://github.com/springfox/springfox/issues/3746
https://github.com/springfox/springfox/issues/3746#issuecomment-830917398

2022-04-09 13:59 UTC, ganados commented on src/main/resources/application.properties
> +spring.datasource.username = ${USERNAME_LOGIN}
poprawione

2022-04-09 14:01 UTC, ganados commented on src/main/java/com/koapti/lazychef/configuration/swagger/SwaggerConfig.java
> +        AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
poprawione

2022-04-09 14:01 UTC, ganados commented on src/main/java/com/koapti/lazychef/configuration/swagger/SwaggerConfig.java
> +                .forPaths(PathSelectors.any())
poprawione

2022-04-09 14:02 UTC, ganados commented on src/main/java/com/koapti/lazychef/LazychefApplication.java
> +@SpringBootApplication()
Nie, jakas pozostałość po poprawkach

2022-04-15 11:09 UTC, fizo99 commented on src/main/java/com/koapti/lazychef/configuration/swagger/SwaggerConfig.java
> +        AuthorizationScope[] authorizationScopes = new AuthorizationScope[]{new AuthorizationScope("global", "accessEverything")};
zmienilbym na var

2022-04-15 11:14 UTC, fizo99 requested changes

2022-04-15 11:14 UTC, fizo99 commented on src/main/java/com/koapti/lazychef/model/entity/Order.java
> +@Table(name = "\"order\"")
czemu tutaj w nazwie tabeli sa " ?

2022-04-15 11:14 UTC, fizo99 commented on src/main/java/com/koapti/lazychef/model/types/RoleType.java
> +    COOKER,
COOK

2022-04-16 13:52 UTC, ganados commented on src/main/java/com/koapti/lazychef/model/entity/Order.java
> +@Table(name = "\"order\"")
musialo dodac z automatu, poprawiłem

2022-04-16 13:52 UTC, ganados commented on src/main/java/com/koapti/lazychef/model/types/RoleType.java
> +    COOKER,
poprawione

2022-04-16 14:30 UTC, fizo99 approved these changes

2022-04-16 14:31 UTC, merged